### ISSUE TITLE
Investigate concurrent inference across threads with one model

### ISSUE THREAD

**Issue by philpax** [rustformers/llama-rs#95]
`hlhr202` raised this [on the Discord](https://discord.com/channels/1085885067601137734/1085885068465147949/1091243245914292234): the ability to infer with multiple sessions simultaneously (assuming you have the computational resources).

It'd look something like this:

```rust
let model = Arc::new(/* create model */);
let t1 = std::thread::spawn({
  let model = model.clone();
  move || {
    let session = /* create session */
    session.inference_with_prompt(...);
  });

let t2 = std::thread::spawn({
  let model = model.clone();
  move || {
    let session = /* create session */
    session.inference_with_prompt(...);
  });
```

The main blocker is adding `Send+Sync` where appropriate and ensuring that no thread safety invariants are broken.

**Comment by hlhr202** [comment]
So did you try this? not applicable for current version right?

**Comment by philpax** [comment]
I haven't tried this, but I wouldn't expect it to work as the `Model` has internal pointers

**Comment by KerfuffleV2** [comment]
A way around that would be to just have one thread and multiple sessions. You could generate tokens round robin from each of them, it doesn't actually have to be parallel since the actual generation already is.

You'd probably want to use a small batch size for feeding the prompt, but I actually haven't seen that really make a difference regardless of whether it's big or small.

**Comment by jon-chuang** [comment]
> You could generate tokens round robin from each of them, it doesn't actually have to be parallel since the actual generation already is.

I don't think this makes sense. What makes more sense to me is to have multiple CLIs all loading the same read-only mmaped model (see: https://github.com/rustformers/llama-rs/pull/129). They maintain their own local in-memory state and context windows.

**Comment by KerfuffleV2** [comment]
> What makes more sense to me is to have multiple CLIs all loading the same read-only mmaped model (see: https://github.com/rustformers/llama-rs/pull/129). They maintain their own local in-memory state and context windows.

You basically just described a session in llama-rs. Sessions are created from a model and just involve the mutable part. So you could create a bunch of sessions and they'd share the actual loaded model.

**Comment by jon-chuang** [comment]
No, what I meant is that the model will not be passed around. The thing that is cross thread is the mmaped file.

**Comment by KerfuffleV2** [comment]
I don't think we're talking about the same thing here. In llama-rs you can make sessions off of a loaded model. Those sessions all share the actual model data and have their own private state.

If you wanted to simulate running multiple incarnations of the model in parallel, you could, for example, make two sessions and generate a token round robin style, first from the first session, then from the second one, and so on.

There isn't really a disadvantage to doing it that way because generating each token is already parallel, so running both at the same time wouldn't really do anything. The approach I'm describing would be possible with the current version, and no special support for doing stuff across threads would be needed because all the sessions I'm talking about would be running in the same thread.

**Comment by jon-chuang** [comment]
```
error[E0277]: `NonNull<ggml_sys::ggml_tensor>` cannot be shared between threads safely
   --> llama-cli/src/main.rs:263:30
    |
263 |     let routes = warp::get().and(
    |                              ^^^ `NonNull<ggml_sys::ggml_tensor>` cannot be shared between threads safely

```

**Comment by setzer22** [comment]
To throw in my two cents.

@KerfuffleV2 is absolutely right here. The session API was designed to accommodate for this use case, and can be used already independently of whether mmap is used for loading the models or not. It is not necessary to spawn multiple processes that share the same mmap-ed memory buffers. The idea is that you load the model once, in a single process, and build an application that serves as many queries as you want by spawning as many inference sessions as required. Inference sessions can even be serialized and retrieved later.

Addressing the fact ggml is not thread safe can be done in two ways.

Just in case, for people who don't know, the YOLO way for someone who just wants to get this done is:
```rust
struct MyModel(llama_rs::Model);
unsafe impl Send for MyModel {};
unsafe impl Sync for MyModel {};
```

This is not correct, but is "as safe as the C++ version", meaning that nobody did any work to ensure a ggml context is thread safe (just like in C++), but if you're sure you're not breaking any thread safety rules, Rust will stay out of your way and let you do your thing. In general, I think this should work, because a `Model` is immutable, so its tensor data or the underlying ggml context are never modified after creation.

We can't obviously merge this. But doing the actual work to make sure our ggml bindings are thread-safe (and other kinds of safe) is no easy task.

Another workaround not involving unsafe would be to keep your inference in a single thread. As @KerfuffleV2 already mentioned, inference happens in parallel and should utilize all of your CPU cores. So instead of trying to force the model into being `Send` + `Sync` sothat multiple threads can hold a reference to it, one could implement a thread that serves inference requests sequentially, and uses a mpsc channel (or some equivalent data structure) so other threads can communicate with it. This feels like a more solid architecture that could be implemented today.

**Comment by jon-chuang** [comment]
> That thread runs evaluation on the sessions.

Firstly, I guess llama-rs should only host the CLI as an application, and not a webserver. 

I tried implemented one, but getting the UX to a desirable level is non-trivial and best suited to an external consumer of llama-rs. I went by the unsafe route, which seemed to work fine, but @setzer22 's caveat applies.

For a single-threaded, multi-session manager, I think it's easy to implement it at the core of a webserver around the existing API.

The fact that the ggml thread pool is external to the webserver's tasks (and thus do not block the worker threads) is a plus.

So it seems like an acceptable workaround.

**Comment by philpax** [comment]
After #135, I think I can more safely say that we can chuck `unsafe impl Send/Sync for Model` in, and `unsafe impl Send for InferenceSession`. 

The only thing we'll need to do is more liberally use `&mut` for the GGML types so that it's impossible to write to anything in the `Model` after initial creation - I've done some of this in https://github.com/rustformers/llama-rs/pull/125/commits/34429e02d3ce766eaca779d7d08c497eeed03a1a which I might reproduce on main if that PR doesn't land soon.

**Comment by vv9k** [comment]
I've managed to get something working with multiple sessions running at a time. The basic idea is that there is a thread that reads inference requests and puts them in a queue that is read by another thread that handles the inference. The thread handling inference runs N sessions at a time and gets a token at a time for each session.

If anyone is interested here is the project I'm working on: https://github.com/vv9k/airtifex

It is a webui with a chat and prompt mode and can load all the alpaca/llama/vicuna models using this crate.
