### ISSUE TITLE
Are the enumerated values in `ggml-raw/src/lib.rs` off-by-one after `GGML_OP_NORM`

### ISSUE THREAD

**Issue by saites** [rustformers/llama-rs#98]
[This PR][ggml-update-pr] added the `ggml` RMS norm function, but doesn't seem to have inserted the [`GGML_OP_RMS_NORM`][ggml-ops-c-enum] to [the list of enumerated values][ggml-ops-rust-enum]. I don't think this codebase actually references these constants, but if I understand it right, I think they'll be mismatched. This is outside my expertise, for sure -- so my apologies if I'm misunderstanding this.

If I do understand right, though, the fix is to just add the new operation and increment the other values. I can submit a PR to this end, if you'd like.

I should ask: should the type be defined, as it is now, using `c_int` instead of a Rust `enum` with `#[repr(C)]`? I know [the Rust reference][reprc-enums] says this can be the wrong choice, if the C type actually represents values outside the discriminated ones, but based on their use in `ggml`, that seems unlikely. If it were an `enum`, it'd be easier to match these lists in the future. It would also mean it'd have the default `enum` size and alignment, though since [it's implementation defined][reprc-enums] and depends on compiler flags (perhaps things like [`-fshort-enums`][gcc-enums]?), it's still a guess -- but isn't using `c_int` as well?

[ggml-update-pr]: https://github.com/rustformers/llama-rs/pull/32/files
[ggml-ops-rust-enum]: https://github.com/rustformers/llama-rs/blob/599a35436c64d26225d0cff7ad63a5fb427f15d6/ggml-raw/src/lib.rs#L34
[ggml-ops-c-enum]: https://github.com/rustformers/llama-rs/blob/599a35436c64d26225d0cff7ad63a5fb427f15d6/ggml-raw/ggml/ggml.h#L233
[reprc-enums]: https://doc.rust-lang.org/reference/type-layout.html#reprc-field-less-enums
[gcc-enums]: https://www.gnu.org/software/gnu-c-manual/gnu-c-manual.html#Enumerations

**Comment by philpax** [comment]
Yeah, good spot - I actually realised this myself while updating for #81. Luckily, as you've noticed, they're not actually used - so I went with the much simpler fix of just removing them entirely 😅 

The bindings are based on a cutdown version of bindgen output, so the use of `c_int` is semi-intentional (it matches the `int` enum definition).

Once #81 lands, the op type will be more or less opaque, and I'll close this issue if that's OK with you?

**Comment by saites** [comment]
> so I went with the much simpler fix of just removing them entirely

A very reasonable choice! :laughing: 

Though now I have nothing to contribute :P 

> The bindings are based on a cutdown version of bindgen output, so the use of c_int is semi-intentional

As I said before, I am definitely outside my area of expertise on this. Do you think this would be worthwhile for me investigate to better understand these pieces? Not for this issue -- just my own learning.

> the op type will be more or less opaque, and I'll close this issue if that's OK with you?

Yes, completely reasonable.

Thanks for your awesome work on this project, btw!

**Comment by philpax** [comment]
> As I said before, I am definitely outside my area of expertise on this. Do you think this would be worthwhile for me investigate to better understand these pieces? Not for this issue -- just my own learning.

It's a pretty minor thing, all things considered - C enums use `int` by default (I don't actually think there's a way to specify a different type in C, but there is in C++) - so matching them requires `c_int` on the Rust side. I believe [rust-bindgen](https://github.com/rust-lang/rust-bindgen) generates `c_int` + constants because it can't generally assume they can be mapped to Rust `enum`s.

When I do manual bindings, I usually check if it can be represented exactly in a Rust `enum`, and do so if I can; sometimes I err on the safe side and use constants, then write a Rust `enum` that can be constructed from those constants.

As a learning exercise, I'd just play around with `rust-bindgen` and get a feel for what it outputs :)

> Thanks for your awesome work on this project, btw!

All good! We're glad people are enjoying it 🚀
